name: ImageJCannyScratch
channels:
  - defaults
  - PyPI
dependencies:
  - python=3.9.16
  - matplotlib==3.7.1
  - numpy
  - pip=22.3.1
  - pip:
    - customtkinter
    - opencv_contrib_python==4.6.0.66
    - opencv_python==4.7.0.72
    - opencv_python_headless==4.8.0.74
    - Pillow==10.1.0
    - scikit_image==0.19.3